import {
  ShieldIcon,
  GlobeIcon,
  CompassIcon,
  DocumentsIcon,
  HandshakeIcon,
  PrivacyIcon,
  FamilyIcon,
} from "@/components/icons/BrandIcons";

export const solutionsContent = {
  en: {
    hero: {
      eyebrow: "Solutions",
      title: "Comprehensive solutions for global mobility",
      text: "Every client has their own history and goals — so we don't offer generic services. We help you navigate global mobility and investment migration with the right guidance at every stage.",
    },
    items: [
      {
        icon: ShieldIcon,
        title: "Citizenship by Investment",
        subtitle: "Second citizenship through official government programs",
        text: "We guide clients through obtaining second citizenship via official government programs — matched to your goals and seen through to a successful outcome.",
        status: "available" as const,
      },
      {
        icon: GlobeIcon,
        title: "Residency by Investment",
        subtitle: "An alternative path for some clients",
        text: "For clients where residency, not citizenship, is the better fit — opening options to live, work and plan across jurisdictions.",
        status: "comingSoon" as const,
      },
      {
        icon: CompassIcon,
        title: "Program Selection",
        subtitle: "An individual strategy",
        text: "We assess your goals and circumstances to recommend the program that genuinely fits — based on analysis, not promotion.",
        status: "available" as const,
      },
      {
        icon: PrivacyIcon,
        title: "Due Diligence Guidance",
        subtitle: "Preliminary assessment",
        text: "We help you prepare for the review in advance, minimising questions before they arise.",
        status: "available" as const,
      },
      {
        icon: DocumentsIcon,
        title: "Document Preparation",
        subtitle: "Comprehensive support",
        text: "Full support assembling your document package — requirements explained, every stage covered.",
        status: "available" as const,
      },
      {
        icon: GlobeIcon,
        title: "Translation & Legalisation",
        subtitle: "International documentation",
        text: "Translation, notarisation and legalisation, arranged when your documents need to work internationally.",
        status: "available" as const,
      },
      {
        icon: HandshakeIcon,
        title: "End-to-End Application Support",
        subtitle: "From consultation to citizenship",
        text: "We coordinate the process from selection to review completion — clear, sequential and comfortable throughout.",
        status: "available" as const,
      },
      {
        icon: FamilyIcon,
        title: "Post-Citizenship Support",
        subtitle: "Long-term partnership",
        text: "Our support continues after citizenship is granted — for questions on using your new status.",
        status: "available" as const,
      },
    ],
    future: {
      title: "Growing With Our Clients",
      text: "Our portfolio will grow to include Golden Visa programs, business consulting, relocation, and wealth and family planning.",
    },
    closing: {
      title: "In Closing",
      text: "Every solution starts with understanding your goals. Our task isn't to offer as many programs as possible — it's to help you choose the right one.",
    },
    cta: "Get a Consultation",
  },
  ru: {
    hero: {
      eyebrow: "Решения",
      title: "Комплексные решения для глобальной мобильности",
      text: "У каждого клиента своя история и свои цели — поэтому мы не предлагаем универсальные услуги. Помогаем разобраться в вопросах глобальной мобильности и инвестиционной миграции с сопровождением на каждом этапе.",
    },
    items: [
      {
        icon: ShieldIcon,
        title: "Citizenship by Investment",
        subtitle: "Гражданство за инвестиции через официальные программы",
        text: "Сопровождаем получение второго гражданства через официальные государственные программы — от подбора программы до успешного результата.",
        status: "available" as const,
      },
      {
        icon: GlobeIcon,
        title: "Residency by Investment",
        subtitle: "Альтернативное решение для некоторых клиентов",
        text: "Для тех, кому подходит не гражданство, а статус резидента — открывает возможности для жизни, бизнеса и планирования в разных юрисдикциях.",
        status: "comingSoon" as const,
      },
      {
        icon: CompassIcon,
        title: "Выбор программы",
        subtitle: "Индивидуальная стратегия",
        text: "Оцениваем ваши цели и ситуацию, чтобы порекомендовать программу, которая действительно подходит — на основе анализа, а не продвижения.",
        status: "available" as const,
      },
      {
        icon: PrivacyIcon,
        title: "Due Diligence",
        subtitle: "Предварительная оценка",
        text: "Помогаем заранее подготовиться к проверке благонадёжности, снижая риск лишних вопросов.",
        status: "available" as const,
      },
      {
        icon: DocumentsIcon,
        title: "Подготовка документов",
        subtitle: "Комплексное сопровождение",
        text: "Полное сопровождение при сборе документов — с объяснением требований на каждом этапе.",
        status: "available" as const,
      },
      {
        icon: GlobeIcon,
        title: "Переводы и легализация",
        subtitle: "Международная документация",
        text: "Перевод, нотариальное заверение и легализация — когда документы нужно использовать за рубежом.",
        status: "available" as const,
      },
      {
        icon: HandshakeIcon,
        title: "Сопровождение процесса",
        subtitle: "От консультации до получения гражданства",
        text: "Координируем процесс от выбора программы до завершения рассмотрения — понятно и последовательно.",
        status: "available" as const,
      },
      {
        icon: FamilyIcon,
        title: "Поддержка после получения гражданства",
        subtitle: "Долгосрочное сотрудничество",
        text: "Поддержка продолжается и после получения гражданства — по вопросам использования нового статуса.",
        status: "available" as const,
      },
    ],
    future: {
      title: "Развитие международных решений",
      text: "Наш портфель будет расширяться: программы Golden Visa, международный бизнес-консалтинг, релокация, планирование благосостояния.",
    },
    closing: {
      title: "Заключение",
      text: "Каждое решение начинается с понимания ваших целей. Наша задача — не предложить как можно больше программ, а помочь выбрать правильную.",
    },
    cta: "Получить консультацию",
  },
} as const;
